### ISSUE TITLE
Sort places by geolocation 

### ISSUE THREAD

**Issue by smacmullan** [danohart/hellotabs#5]
Get the user's geolocation and sort places by proximity (for today's happy hour page, sort by active happy hours first then sort by proximity)

**Comment by smacmullan** [comment]
I'm working on this in a branch on my fork

**Comment by danohart** [comment]
@smacmullan per this geo PR I just merged, here's what the data looks like now...

`{
  "_id": {
    "$oid": "619057c476b43483d515621b"
  },
  "address": "North Center @ 4265 N Lincoln Ave",
  "alt_id": "37",
  "day": [
    {
      "name": "Sunday",
      "drink_specials": "$17 Half Acre Pitchers, $4 Jameson Whiskey",
      "food_specials": "$6 Brunchie Burger, $6 Buffalo Chicken Breakfast Sandwich",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Monday",
      "drink_specials": "None",
      "food_specials": "25¢ Wings",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Tuesday",
      "drink_specials": "$3 Labatt Blue 22oz Drafts",
      "food_specials": "Half Price Wraps",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Wednesday",
      "drink_specials": "Half Price Wine Bottles, $4 Krombacher",
      "food_specials": "Half Price Burgers",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Thursday",
      "drink_specials": "$4.50 Drafts, $4.50 You-Call-Its",
      "food_specials": "$4.50 Appetizers",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Friday",
      "drink_specials": "$5 Guinness Imperial Drafts, $5 Metropolitan Flywheel Drafts, $5 Select Martinis",
      "food_specials": "$8 All-You-Can-Eat Fish Fry",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    },
    {
      "name": "Saturday",
      "drink_specials": "$5 Michigan Brewery Bottles & Cans, $13 Labatt Blue Pitchers",
      "food_specials": "$6 Wings, $6 Nachos",
      "timeOfDay": {
        "startTime": null,
        "endTime": null
      }
    }
  ],
  "enabled": false,
  "featured": false,
  "lastUpdated": {
    "$date": "2022-12-30T15:14:28.963Z"
  },
  "name": "Wild Goose Bar & Grill",
  "street_address": "4265 N Lincoln Ave",
  "neighborhood": "North Center"
}`

I'm gonna see about getting lat long in the object as well like your example.

**Comment by smacmullan** [comment]
There's a line of code I changed with the place API that I think broke the bar overview page.

Original code:
 .findOne({ _id: new ObjectId(placeId) });

Change: 
.findOne({ _id: placeId });




If I missed geocoding on any places, I've been using the Census geocoder on the street addresses. Free and no rate limit.
https://geocoding.geo.census.gov/geocoder/

**Comment by danohart** [comment]
Functional with https://github.com/danohart/hellotabs/pull/12
