### ISSUE TITLE
Change license to CC BY-NC-SA?

### ISSUE THREAD

**Issue by smacmullan** [danohart/hellotabs#6]
Consider changing the licensing to a CC BY-NC-SA license? (SA instead of ND, "adaptations must be shared under same terms" instead of "no derivatives allowed") As I understand the current license, it disallows non-commercial spinoff work (similar applications forked from this one, standing up instances in different cities).

**Comment by danohart** [comment]
I like it. That's a good example. I would like for derivatives, as long as it's non-commercial. https://github.com/danohart/hellotabs/commit/47ef7926f527eb9402afc6d53e9332a80f45c457
